services:
  db:
    image: docker.io/postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: back
    environment:
      DATABASE_URL: ecto://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      PHX_HOST: ${PHX_HOST}
      FRONT_URL: https://${PHX_HOST}
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${PHX_HOST}
    env_file:
      - .env
    depends_on:
      db:

  frontend:
    build: front
    ports: 
      - "127.0.0.1:8000:80"
    env_file:
      - .env

volumes:
  postgres_data:
