when:
  event: push

variables:
  - &file front/Dockerfile
  - &repo github.com/${CI_REPO}

steps:
  publish:
    image: docker.io/woodpeckerci/plugin-docker-buildx:latest
    settings:
      dockerfile: *file
      repo: *repo
      registry: ghcr.io
      tags: latest
      platforms: linux/arm64/v8
      username: ${CI_REPO_OWNER}
      password:
        from_secret: gh_token
