when:
  - event: push
    branch: master
    path: 'front/**/*'

variables:
  - &file front/Dockerfile
  - &repo ghcr.io/${CI_REPO}-front

steps:
  publish:
    image: docker.io/woodpeckerci/plugin-docker-buildx:latest
    settings:
      dockerfile: *file
      context: front
      repo: *repo
      registry: ghcr.io
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: gh_token
      cache_images:
        - ghcr.io/${CI_REPO}-front:cache
